package com.example.finito.core.presentation.util

object LazyListKeys {
    const val SHOW_COMPLETED_TASKS_TOGGLE = "SHOW_COMPLETED_TASKS_TOGGLE"
    const val PRIMARY_BUTTON = "PRIMARY_BUTTON"
    const val COMPLETED_TASKS_PROGRESS_BAR = "COMPLETED_TASKS_PROGRESS_BAR"
    const val SELECTED_BOARD_INDICATOR = "SELECTED_BOARD_INDICATOR"
    const val NAME_TEXT_FIELD = "NAME_TEXT_FIELD"
    const val DESCRIPTION_TEXT_FIELD = "DESCRIPTION_TEXT_FIELD"
    const val TASK_DATE_TEXT_FIELD = "TASK_DATE_TEXT_FIELD"
    const val TASK_TIME_TEXT_FIELD = "TASK_TIME_TEXT_FIELD"
    const val REMINDER_TEXT_FIELD = "REMINDER_TEXT_FIELD"
    const val TASK_PRIORITY = "TASK_PRIORITY"
    const val CREATE_SUBTASK_BUTTON = "CREATE_SUBTASK_BUTTON"
    const val SUBTASKS_TITLE = "SUBTASKS_TITLE"
    const val LABELS = "LABELS"
}